### ISSUE TITLE
Make signal optional feature

### ISSUE THREAD

**Issue by asv1** [kotauskas/interprocess#6]
**Is your feature request related to a problem? Please describe.**
To reduce dependencies count i propose to make signal is optional.

**Describe the solution you'd like**
Making signal optional in cargo.toml

**Describe alternatives you've considered**

**Additional context**

**Comment by kotauskas** [comment]
Just released version 1.1.1 which adds the `signals` feature flag. It's enabled by default for compatibility, so you can disable it like this:
```toml
[dependencies]
interprocess = { version = "1.1", default-features = false }
```
